FROM ubuntu:24.04

ENV GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git

RUN apt-get update -y && apt-get install -y apt-utils vim curl sudo git
RUN apt-get install -y gcc make pip python3 python3.12-venv
#RUN source venv/bin/activate
RUN pip cache remove llama_cpp_python

RUN CMAKE_ARGS="-DLLAMA_METAL=off" pip install instructlab --extra-index-url=https://download.pytorch.org/whl/cpu --break-system-packages

RUN _ILAB_COMPLETE=bash_source ilab > ~/.ilab-complete.bash
RUN echo ". ~/.ilab-complete.bash" >> ~/.bashrc

